name: june_listener_template
description: "Listen Template in JuneFlow Architecture."
#publish_to: 'none'
repository: https://github.com/juneflow-songdo/june_listener_template

version: 1.0.1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router:
  june_flow_util:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/module/june_listener_template/
  uses-material-design: true